---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family | lower == 'debian'

  roles:
    - role: egdoc.flatpak
      become: true
      flatpak_remotes:
        - name: flathub
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          installed_flatpaks:
            - ca._0ldsk00l.Nestopia
